version: "3.9"
services:
  front:
    build: ./aoe-frontend
    ports:
      - "80:80"
  back:
    build: 
      context: ./aoe-backend
      dockerfile: dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./aoe-backend/db/data.json:/app/db/data.json
